const productos = [{
    id: 1,
    foto: '../img/musculosa.webp',
    nombre: "REMERA MUSCULOSA",
    precio: 6000,
    categoria: "remera",
    cantidad: 1,
},
{
    id: 2,
    foto: '../img/mangalarga.jpg',
    nombre: "REMERA MANGA LARGA",
    precio: 6500,
    categoria: "remera",
    cantidad: 1,
},
{
    id: 3,
    foto: "../img/overside.webp",
    nombre: "REMERA OVERSIDE",
    precio: 7000,
    categoria: "remera",
    cantidad: 1,
},
{
    id: 4,
    foto: '../img/gorra plana.jpg',
    nombre: "GORRA PLANA",
    precio: 2999,
    categoria: "gorras",
    cantidad: 1,
},
{
    id: 5,
    foto: '../img/visra.webp',
    nombre: "GORRA TIPO VISERA",
    precio: 2800,
    categoria: "gorras",
    cantidad: 1,
},
{
    id: 6,
    foto: "../img/PILUSO.jpg",
    nombre: "PILUSO",
    precio: 3100,
    categoria: "gorras",
    cantidad: 1,
},
{
    id: 7,
    foto: '../img/shortdep.webp',
    nombre: "SHORT DEPORTIVO",
    precio: 1800,
    categoria: "Short",
    cantidad: 1,
},
{
    id: 8,
    foto: '../img/shortbaño.jpeg',
    nombre: "SHORT DE BAÑO",
    precio: 2500,
    categoria: "Short",
    cantidad: 1,
},
{
    id: 9,
    foto: '../img/sastero.jpg',
    nombre: "SHORT SASTERO",
    precio: 3000,
    categoria: "Short",
    cantidad: 1,
},
];